services:
  webstrom-frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG:-latest}

    environment:
      - PORT=8922
      - BE_PROTOCOL=http
      - BE_HOSTNAME=localhost
      - BE_PORT=8920
      - BE_FORWARDED_HOST=test.strom.sk
      - BE_FORWARDED_PROTO=https

    network_mode: host

    restart: always
