services:
  webstrom-frontend:
    build:
      dockerfile: deployment/local-mac/Dockerfile
      context: ../..
      args:
        - BE_PROTOCOL=http
        - BE_HOSTNAME=host.docker.internal
        - BE_PORT=8000
        - BE_PREFIX=/api

    image: webstrom-test-frontend

    environment:
      - PORT=3000
      - BE_PROTOCOL=http
      - BE_HOSTNAME=host.docker.internal
      - BE_PORT=8000
      - BE_PREFIX=/api

    ports:
      - '3000:3000'

    restart: always
