version: '3'

services:
  webstrom-frontend:
    build:
      dockerfile: deployment/Dockerfile
      context: ..
      args:
        - BE_PROTOCOL=http
        - BE_HOSTNAME=localhost
        - BE_PORT=8920
        - BE_FORWARDED_HOST=test.strom.sk
        - BE_FORWARDED_PROTO=https
        - DEBUG=true

    image: webstrom-test-frontend

    environment:
      - PORT=8922
      - BE_PROTOCOL=http
      - BE_HOSTNAME=localhost
      - BE_PORT=8920
      - BE_FORWARDED_HOST=test.strom.sk
      - BE_FORWARDED_PROTO=https
      - DEBUG=true

    network_mode: host

    restart: always
