version: '3'

services:
  webstrom-frontend:
    build:
      dockerfile: deployment/Dockerfile
      context: ..
      args:
        - BE_PROTOCOL=http
        - BE_HOSTNAME=localhost
        - BE_PORT=8920

    image: webstrom-test-frontend

    environment:
      - PORT=8922
      - BE_PROTOCOL=http
      - BE_HOSTNAME=localhost
      - BE_PORT=8920

    network_mode: host

    restart: always
