version: "3"

services:
  webstrom-frontend:
    build:
      dockerfile: deployment/Dockerfile
      context: ..
      args:
        - NEXT_PUBLIC_BE_PORT=8920

    image: webstrom-test-frontend

    environment:
      - PORT=8922
      - NEXT_PUBLIC_BE_PORT=8920

    network_mode: host

    restart: always
