name: Deploy Production Environment

on: workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      project_name: webstrom-prod
      port: '8932'
      be_protocol: 'http'
      be_hostname: 'localhost'
      be_port: '8930'
      be_forwarded_proto: 'https'
      be_forwarded_host: 'strom.sk'
    secrets:
      ssh_private_key: ${{ secrets.WEBSTROM_DEPLOY_SSH_PRIVATE_KEY }}
