name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Temporarily save SSH key to file
        run: |
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > deploy_key
          chmod 600 deploy_key
      - name: Run deployment via SSH
        run: ssh -o "StrictHostKeyChecking=no" -i deploy_key webstrom@server.strom.sk deploy-frontend

      - name: Clean SSH key
        run: rm -f deploy_key
