name: Deploy Test Environment

on: workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: test
      port: '8922'
      backend_port: '8920'
      forwarded_host: test.strom.sk
    secrets:
      ssh_private_key: ${{ secrets.WEBSTROM_DEPLOY_SSH_PRIVATE_KEY }}
