name: Deploy Prod Environment

on: workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: prod
      port: '8932'
      backend_port: '8930'
      forwarded_host: strom.sk
    secrets:
      ssh_private_key: ${{ secrets.WEBSTROM_DEPLOY_SSH_PRIVATE_KEY }}
