name: Deploy Test Environment

on:
  workflow_dispatch:
  # push:
  #   branches: [master, main]

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      project_name: webstrom-test
      port: '8922'
      be_protocol: 'http'
      be_hostname: 'localhost'
      be_port: '8920'
      be_forwarded_proto: 'https'
      be_forwarded_host: 'test.strom.sk'
    secrets:
      ssh_private_key: ${{ secrets.WEBSTROM_DEPLOY_SSH_PRIVATE_KEY }}
